// nextjs/components/counter.jsx
import { useState } from 'react';

export default function Counter({ children, count: initialCount }) {
  const [count, setCount] = useState(initialCount);
  const add = () => setCount((i) => i + 1);
  const subtract = () => setCount((i) => i - 1);

  return (
    <>
      <div className="counter">
        <button onClick={subtract}>-</button>
        <pre>{count}</pre>
        <button onClick={add}>+</button>
      </div>
      <div className="children">{children}</div>
    </>
  );
}

// nuxt/components/Counter.vue
<template>
<div className="counter">
  <button @click="subtract">-</button>
  <pre>{{count}}</pre>
  <button @click="add">+</button>
</div>
</template>

<script>
export default {
  props: ['initialCount'],
  data() {
    return {
      title: "Counter",
      count: this.initialCount,
    };
  },
  methods: {
    subtract() {
      this.count--;
    },
    add() {
      this.count++;
    }
  }
};
</script>
